### ISSUE TITLE
Add all results to database?

### ISSUE THREAD

**Issue by Zhaoyang-XU** [ProLint/ProLint#17]
Dear bisejdiu,

Is there any way we can store the results to the database page and restore previous results after docker reboot?

Thanks !

All the best,
John

**Comment by bisejdiu** [comment]
Hi John, 

I haven't tested this but previously calculated results should be available by default. Just make sure to not force shut down the docker images (i.e. allow for docker to gracefully stop the images). After creating the docker build for the first time, you can also comment lines 4-6 here https://github.com/ProLint/ProLint/blob/main/prolint/entrypoint.sh before restarting the images and that should work too. 

Storing results to the database page is a bit more challenging and depends on how comfortable you are using django. Basically, you want to get all objects within the `FileMD` model and then only keep those that have their status equal to `SUCCESSFUL`, and then forward them to a template that you create. Alternatively, you can use the `ExploreResults` model that already exists in the `explore` app and create a view that you can use to store objects from `FileMD` to `ExploreResults`. This would much more efficient since you would not have to loop through all objects every time you want to show results.

**Comment by Zhaoyang-XU** [comment]
Hi @bisejdiu,

Thanks for your detailed instructions. I will try the " comment lines 4-6” way  and see if it works for me.

Kind regards,
John
